name: ci

# Design tokens configuration data
env:
  tokens-file: tokens.json
  platforms: "scss,css,ios-swift"
  output: generated

# Execute runner when the tokens file is pushed to 'main' branch or on a pull request event to 'main'
on:
  pull_request:
  push:
    branches:
      - main
    # Can't use the ${{env.tokens-file}} environment variable here, because they can only be used
    # in a workflow step or an action.
    # See: https://docs.github.com/en/enterprise-server@3.0/actions/learn-github-actions/environment-variables#about-environment-variables
    # Another solution could be, to add a conditional on every job to check if the file has changed :(
    paths:
      - tokens.json

jobs:
  transform:
    name: Transform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Transform tokens
        id: transform
        uses: Flutter-Global/design-tokens@master
        with:
          input: ${{env.tokens-file}}
          platforms: ${{env.platforms}}
          output: ${{env.output}}

  commit:
    name: Commit
    runs-on: ubuntu-latest
    needs: transform
    outputs:
      commit-sha: ${{ steps.automatic-commit.outputs.commit_hash }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Download assets artifact
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: ${{env.output}}

      - name: Display downloaded assets files
        run: ls -R
        working-directory: ${{env.output}}

      - name: Automatic commit
        id: automatic-commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(github-actions-bot): add generated assets"
