name: release

# Execute runner when the generated files are pushed to 'main' branch or on a pull request event to 'main'
on:
  pull_request:
  push:
    paths:
      - "**.css"
      - "**.scss"
      - "**.swift"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
